image: docker-registry.linagora.com:5000/linshare-snapshots/linshare-dind:latest

stages:
  - build

build:
  stage: build
  tags:
    - docker
  services:
      - name: docker-registry.linagora.com:5000/linshare-snapshots/linshare-dind:latest
        alias: docker-dind
  variables:
      DOCKER_HOST: "tcp://docker-dind"
  script:
    - docker build .
  except:
    - master@linagora/lgs/linshare/saas/linshare-ui-user-dockerfile
    - /^maintenance-.*/@linagora/lgs/linshare/saas/linshare-ui-user-dockerfile
    - tags@linagora/lgs/linshare/saas/linshare-ui-user-dockerfile
