image: docker-registry.linagora.com:5000/linshare-snapshots/linshare-dind:latest

stages:
  - build

build:
  stage: build
  tags:
    - docker
  services:
      - name: docker-registry.linagora.com:5000/linshare-snapshots/linshare-dind:latest
        alias: docker-dind
  variables:
      DOCKER_HOST: "tcp://docker-dind:2375"
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: ""
  before_script:
  - apk update && apk add git 
  - git --version

  script:
    - docker build .
# only:
#   - master@linagora/lgs/linshare/saas/linshare-ui-user-dockerfile
#   - /^maintenance-.*/@linagora/lgs/linshare/saas/linshare-ui-user-dockerfile
#   - tags@linagora/lgs/linshare/saas/linshare-ui-user-dockerfile
